package com.example.ioclookup.data.export

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import com.example.ioclookup.domain.model.LookupResult
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class ExportService @Inject constructor(
    @ApplicationContext private val context: Context
) {
    private val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())

    fun asPlainText(result: LookupResult): String = buildString {
        appendLine("═══════════════════════════════════════")
        appendLine("  IOC LOOKUP REPORT")
        appendLine("═══════════════════════════════════════")
        appendLine()
        appendLine("IOC         : ${result.ioc}")
        appendLine("Type        : ${result.iocType.displayName}")
        appendLine("Verdict     : ${result.verdict.displayName.uppercase()}")
        appendLine("Timestamp   : ${dateFormat.format(Date(result.timestamp))}")
        appendLine()

        result.vtResult?.let { vt ->
            appendLine("── VirusTotal ──────────────────────────")
            appendLine("Detection   : ${vt.detectionLabel}")
            appendLine("Reputation  : ${vt.reputation}")
            if (vt.categories.isNotEmpty()) appendLine("Categories  : ${vt.categories.joinToString(", ")}")
            if (vt.tags.isNotEmpty()) appendLine("Tags        : ${vt.tags.joinToString(", ")}")
            appendLine()
        }

        result.abuseResult?.let { abuse ->
            appendLine("── AbuseIPDB ────────────────────────────")
            appendLine("Confidence  : ${abuse.abuseConfidenceScore}%")
            appendLine("Reports     : ${abuse.totalReports} (${abuse.numDistinctUsers} users)")
            abuse.lastReportedAt?.let { appendLine("Last Report : $it") }
            abuse.countryCode?.let { appendLine("Country     : $it") }
            abuse.isp?.let { appendLine("ISP         : $it") }
            abuse.usageType?.let { appendLine("Usage       : $it") }
            if (abuse.isTor) appendLine("Tor         : Yes")
            appendLine()
        }

        result.shodanResult?.let { sh ->
            appendLine("── Shodan ───────────────────────────────")
            if (sh.ports.isNotEmpty()) appendLine("Open Ports  : ${sh.ports.joinToString(", ")}")
            sh.country?.let { appendLine("Country     : $it") }
            sh.org?.let { appendLine("Org         : $it") }
            sh.os?.let { appendLine("OS          : $it") }
            if (sh.cves.isNotEmpty()) appendLine("CVEs        : ${sh.cves.joinToString(", ")}")
            appendLine()
        }

        result.otxResult?.let { otx ->
            appendLine("── AlienVault OTX ───────────────────────")
            appendLine("Pulses      : ${otx.pulseCount}")
            if (otx.tags.isNotEmpty()) appendLine("Tags        : ${otx.tags.take(10).joinToString(", ")}")
            if (otx.malwareFamilies.isNotEmpty()) appendLine("Malware     : ${otx.malwareFamilies.joinToString(", ")}")
            if (otx.adversaries.isNotEmpty()) appendLine("Adversaries : ${otx.adversaries.joinToString(", ")}")
            appendLine()
        }

        appendLine("═══════════════════════════════════════")
        appendLine("Generated by IOC Lookup")
    }

    fun asPdf(result: LookupResult): File {
        val dir = context.cacheDir
        val file = File(dir, "ioc_report_${System.currentTimeMillis()}.pdf")

        val pdfDocument = PdfDocument()
        // A4 size: 595 x 842 points
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
        var page = pdfDocument.startPage(pageInfo)
        var canvas = page.canvas

        val titlePaint = Paint().apply {
            color = Color.BLACK
            textSize = 20f
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.BOLD)
        }
        val sectionPaint = Paint().apply {
            color = Color.BLACK
            textSize = 14f
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.BOLD)
        }
        val labelPaint = Paint().apply {
            color = Color.BLACK
            textSize = 10f
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.BOLD)
        }
        val valuePaint = Paint().apply {
            color = Color.BLACK
            textSize = 10f
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.NORMAL)
        }
        val footerPaint = Paint().apply {
            color = Color.GRAY
            textSize = 8f
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.NORMAL)
            textAlign = Paint.Align.CENTER
        }
        val linePaint = Paint().apply {
            color = Color.DKGRAY
            strokeWidth = 1f
        }

        var currentY = 50f
        val startX = 50f
        val colWidth = 150f

        fun checkPageBreak(neededHeight: Float = 50f) {
            if (currentY + neededHeight > 800f) {
                pdfDocument.finishPage(page)
                page = pdfDocument.startPage(pageInfo)
                canvas = page.canvas
                currentY = 50f
            }
        }

        fun drawLine() {
            canvas.drawLine(startX, currentY, 545f, currentY, linePaint)
            currentY += 15f
        }

        // Title
        canvas.drawText("IOC LOOKUP REPORT", startX, currentY, titlePaint)
        currentY += 10f
        drawLine()
        currentY += 10f

        fun addRow(label: String, value: String, highlight: Boolean = false) {
            checkPageBreak(30f)
            canvas.drawText(label, startX, currentY, labelPaint)
            val valP = if (highlight) labelPaint else valuePaint
            
            // Wrap text logic very simply
            val maxLen = 65
            var valStr = value
            if (valStr.length > maxLen) {
                valStr = valStr.substring(0, maxLen - 3) + "..."
            }
            canvas.drawText(valStr, startX + colWidth, currentY, valP)
            currentY += 20f
        }

        addRow("IOC", result.ioc)
        addRow("Type", result.iocType.displayName)
        addRow("Verdict", result.verdict.displayName.uppercase(), highlight = true)
        addRow("Timestamp", dateFormat.format(Date(result.timestamp)))
        currentY += 15f

        fun addSection(title: String, rows: List<Pair<String, String>>) {
            checkPageBreak(50f)
            canvas.drawText(title, startX, currentY, sectionPaint)
            currentY += 10f
            drawLine()
            for ((lbl, vl) in rows) {
                addRow(lbl, vl)
            }
            currentY += 10f
        }

        result.vtResult?.let { vt ->
            val rows = mutableListOf(
                "Detection" to vt.detectionLabel,
                "Reputation" to "${vt.reputation}"
            )
            if (vt.categories.isNotEmpty()) rows += "Categories" to vt.categories.joinToString(", ")
            if (vt.tags.isNotEmpty()) rows += "Tags" to vt.tags.joinToString(", ")
            addSection("VirusTotal", rows)
        }

        result.abuseResult?.let { abuse ->
            val rows = mutableListOf(
                "Confidence Score" to "${abuse.abuseConfidenceScore}%",
                "Total Reports" to "${abuse.totalReports} from ${abuse.numDistinctUsers} users"
            )
            abuse.lastReportedAt?.let { rows += "Last Reported" to it }
            abuse.isp?.let { rows += "ISP" to it }
            addSection("AbuseIPDB", rows)
        }

        result.shodanResult?.let { sh ->
            val rows = mutableListOf<Pair<String, String>>()
            if (sh.ports.isNotEmpty()) rows += "Open Ports" to sh.ports.joinToString(", ")
            sh.org?.let { rows += "Organization" to it }
            sh.country?.let { rows += "Country" to it }
            if (sh.cves.isNotEmpty()) rows += "CVEs" to sh.cves.joinToString(", ")
            if (rows.isNotEmpty()) addSection("Shodan", rows)
        }

        result.otxResult?.let { otx ->
            val rows = mutableListOf("Pulse Count" to "${otx.pulseCount}")
            if (otx.tags.isNotEmpty()) rows += "Tags" to otx.tags.take(15).joinToString(", ")
            if (otx.malwareFamilies.isNotEmpty()) rows += "Malware Families" to otx.malwareFamilies.joinToString(", ")
            addSection("AlienVault OTX", rows)
        }

        // Footer
        canvas.drawText("Generated by IOC Lookup • ${dateFormat.format(Date())}", 595f / 2f, 820f, footerPaint)

        pdfDocument.finishPage(page)

        FileOutputStream(file).use { out ->
            pdfDocument.writeTo(out)
        }
        pdfDocument.close()

        return file
    }
}
