package com.example.ioclookup.data.export

import android.content.Context
import com.example.ioclookup.domain.model.LookupResult
import com.example.ioclookup.domain.model.SourceResult
import com.itextpdf.kernel.colors.ColorConstants
import com.itextpdf.kernel.colors.DeviceRgb
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Cell
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.element.Table
import com.itextpdf.layout.element.LineSeparator
import com.itextpdf.layout.properties.TextAlignment
import com.itextpdf.layout.properties.UnitValue
import com.itextpdf.kernel.pdf.canvas.draw.SolidLine
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class ExportService @Inject constructor(
    @ApplicationContext private val context: Context
) {
    private val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())

    fun asPlainText(result: LookupResult): String = buildString {
        appendLine("═══════════════════════════════════════")
        appendLine("  IOC LOOKUP REPORT")
        appendLine("═══════════════════════════════════════")
        appendLine()
        appendLine("IOC         : ${result.ioc}")
        appendLine("Type        : ${result.iocType.displayName}")
        appendLine("Verdict     : ${result.verdict.displayName.uppercase()}")
        appendLine("Timestamp   : ${dateFormat.format(Date(result.timestamp))}")
        appendLine()

        result.vtResult?.let { vt ->
            appendLine("── VirusTotal ──────────────────────────")
            appendLine("Detection   : ${vt.detectionLabel}")
            appendLine("Reputation  : ${vt.reputation}")
            if (vt.categories.isNotEmpty()) appendLine("Categories  : ${vt.categories.joinToString(", ")}")
            if (vt.tags.isNotEmpty()) appendLine("Tags        : ${vt.tags.joinToString(", ")}")
            appendLine()
        }

        result.abuseResult?.let { abuse ->
            appendLine("── AbuseIPDB ────────────────────────────")
            appendLine("Confidence  : ${abuse.abuseConfidenceScore}%")
            appendLine("Reports     : ${abuse.totalReports} (${abuse.numDistinctUsers} users)")
            abuse.lastReportedAt?.let { appendLine("Last Report : $it") }
            abuse.countryCode?.let { appendLine("Country     : $it") }
            abuse.isp?.let { appendLine("ISP         : $it") }
            abuse.usageType?.let { appendLine("Usage       : $it") }
            if (abuse.isTor) appendLine("Tor         : Yes")
            appendLine()
        }

        result.shodanResult?.let { sh ->
            appendLine("── Shodan ───────────────────────────────")
            if (sh.ports.isNotEmpty()) appendLine("Open Ports  : ${sh.ports.joinToString(", ")}")
            sh.country?.let { appendLine("Country     : $it") }
            sh.org?.let { appendLine("Org         : $it") }
            sh.os?.let { appendLine("OS          : $it") }
            if (sh.cves.isNotEmpty()) appendLine("CVEs        : ${sh.cves.joinToString(", ")}")
            appendLine()
        }

        result.otxResult?.let { otx ->
            appendLine("── AlienVault OTX ───────────────────────")
            appendLine("Pulses      : ${otx.pulseCount}")
            if (otx.tags.isNotEmpty()) appendLine("Tags        : ${otx.tags.take(10).joinToString(", ")}")
            if (otx.malwareFamilies.isNotEmpty()) appendLine("Malware     : ${otx.malwareFamilies.joinToString(", ")}")
            if (otx.adversaries.isNotEmpty()) appendLine("Adversaries : ${otx.adversaries.joinToString(", ")}")
            appendLine()
        }

        appendLine("═══════════════════════════════════════")
        appendLine("Generated by IOC Lookup")
    }

    fun asPdf(result: LookupResult): File {
        val dir = context.cacheDir
        val file = File(dir, "ioc_report_${System.currentTimeMillis()}.pdf")

        val pdfDoc = PdfDocument(PdfWriter(file))
        val document = Document(pdfDoc)

        val headerColor = DeviceRgb(20, 20, 40)
        val accentColor = when (result.verdict.name) {
            "MALICIOUS" -> DeviceRgb(231, 76, 60)
            "SUSPICIOUS" -> DeviceRgb(243, 156, 18)
            "CLEAN" -> DeviceRgb(46, 204, 113)
            else -> DeviceRgb(149, 165, 166)
        }

        // Title
        document.add(
            Paragraph("IOC LOOKUP REPORT")
                .setFontSize(20f)
                .setBold()
                .setFontColor(headerColor)
        )
        document.add(LineSeparator(SolidLine()))

        // Summary Table
        val summaryTable = Table(UnitValue.createPercentArray(floatArrayOf(30f, 70f)))
            .setWidth(UnitValue.createPercentValue(100f))

        fun addRow(label: String, value: String, highlight: Boolean = false) {
            val labelCell = Cell().add(Paragraph(label).setBold().setFontSize(10f))
                .setBackgroundColor(DeviceRgb(240, 240, 250))
            val valueCell = Cell().add(
                Paragraph(value).setFontSize(10f).apply {
                    if (highlight) setFontColor(accentColor)
                }
            )
            summaryTable.addCell(labelCell)
            summaryTable.addCell(valueCell)
        }

        addRow("IOC", result.ioc)
        addRow("Type", result.iocType.displayName)
        addRow("Verdict", result.verdict.displayName.uppercase(), highlight = true)
        addRow("Timestamp", dateFormat.format(Date(result.timestamp)))

        document.add(summaryTable)
        document.add(Paragraph("\n"))

        // Per-source sections
        result.vtResult?.let { vt ->
            document.add(Paragraph("VirusTotal").setBold().setFontSize(14f).setFontColor(headerColor))
            document.add(LineSeparator(SolidLine()))
            val tbl = Table(UnitValue.createPercentArray(floatArrayOf(35f, 65f)))
                .setWidth(UnitValue.createPercentValue(100f))
            tbl.addCell(Cell().add(Paragraph("Detection").setBold()))
            tbl.addCell(Cell().add(Paragraph(vt.detectionLabel).setFontColor(if (vt.detectionCount > 0) accentColor else ColorConstants.BLACK)))
            tbl.addCell(Cell().add(Paragraph("Reputation").setBold()))
            tbl.addCell(Cell().add(Paragraph("${vt.reputation}")))
            if (vt.categories.isNotEmpty()) {
                tbl.addCell(Cell().add(Paragraph("Categories").setBold()))
                tbl.addCell(Cell().add(Paragraph(vt.categories.joinToString(", "))))
            }
            if (vt.tags.isNotEmpty()) {
                tbl.addCell(Cell().add(Paragraph("Tags").setBold()))
                tbl.addCell(Cell().add(Paragraph(vt.tags.joinToString(", "))))
            }
            document.add(tbl)
            document.add(Paragraph("\n"))
        }

        result.abuseResult?.let { abuse ->
            document.add(Paragraph("AbuseIPDB").setBold().setFontSize(14f).setFontColor(headerColor))
            document.add(LineSeparator(SolidLine()))
            val tbl = Table(UnitValue.createPercentArray(floatArrayOf(35f, 65f)))
                .setWidth(UnitValue.createPercentValue(100f))
            tbl.addCell(Cell().add(Paragraph("Confidence Score").setBold()))
            tbl.addCell(Cell().add(Paragraph("${abuse.abuseConfidenceScore}%")))
            tbl.addCell(Cell().add(Paragraph("Total Reports").setBold()))
            tbl.addCell(Cell().add(Paragraph("${abuse.totalReports} from ${abuse.numDistinctUsers} users")))
            abuse.lastReportedAt?.let {
                tbl.addCell(Cell().add(Paragraph("Last Reported").setBold()))
                tbl.addCell(Cell().add(Paragraph(it)))
            }
            abuse.isp?.let {
                tbl.addCell(Cell().add(Paragraph("ISP").setBold()))
                tbl.addCell(Cell().add(Paragraph(it)))
            }
            document.add(tbl)
            document.add(Paragraph("\n"))
        }

        result.shodanResult?.let { sh ->
            document.add(Paragraph("Shodan").setBold().setFontSize(14f).setFontColor(headerColor))
            document.add(LineSeparator(SolidLine()))
            val tbl = Table(UnitValue.createPercentArray(floatArrayOf(35f, 65f)))
                .setWidth(UnitValue.createPercentValue(100f))
            if (sh.ports.isNotEmpty()) {
                tbl.addCell(Cell().add(Paragraph("Open Ports").setBold()))
                tbl.addCell(Cell().add(Paragraph(sh.ports.joinToString(", "))))
            }
            sh.org?.let {
                tbl.addCell(Cell().add(Paragraph("Organization").setBold()))
                tbl.addCell(Cell().add(Paragraph(it)))
            }
            sh.country?.let {
                tbl.addCell(Cell().add(Paragraph("Country").setBold()))
                tbl.addCell(Cell().add(Paragraph(it)))
            }
            if (sh.cves.isNotEmpty()) {
                tbl.addCell(Cell().add(Paragraph("CVEs").setBold()))
                tbl.addCell(Cell().add(Paragraph(sh.cves.joinToString(", "))))
            }
            document.add(tbl)
            document.add(Paragraph("\n"))
        }

        result.otxResult?.let { otx ->
            document.add(Paragraph("AlienVault OTX").setBold().setFontSize(14f).setFontColor(headerColor))
            document.add(LineSeparator(SolidLine()))
            val tbl = Table(UnitValue.createPercentArray(floatArrayOf(35f, 65f)))
                .setWidth(UnitValue.createPercentValue(100f))
            tbl.addCell(Cell().add(Paragraph("Pulse Count").setBold()))
            tbl.addCell(Cell().add(Paragraph("${otx.pulseCount}")))
            if (otx.tags.isNotEmpty()) {
                tbl.addCell(Cell().add(Paragraph("Tags").setBold()))
                tbl.addCell(Cell().add(Paragraph(otx.tags.take(15).joinToString(", "))))
            }
            if (otx.malwareFamilies.isNotEmpty()) {
                tbl.addCell(Cell().add(Paragraph("Malware Families").setBold()))
                tbl.addCell(Cell().add(Paragraph(otx.malwareFamilies.joinToString(", "))))
            }
            document.add(tbl)
            document.add(Paragraph("\n"))
        }

        document.add(
            Paragraph("Generated by IOC Lookup • ${dateFormat.format(Date())}")
                .setFontSize(8f)
                .setFontColor(DeviceRgb(149, 165, 166))
                .setTextAlignment(TextAlignment.CENTER)
        )

        document.close()
        return file
    }
}
