package com.example.ioclookup.data.export

import android.content.Context
import com.example.ioclookup.domain.model.LookupResult
import com.example.ioclookup.domain.model.SourceResult
import com.lowagie.text.Cell
import com.lowagie.text.Document
import com.lowagie.text.Element
import com.lowagie.text.Font
import com.lowagie.text.Paragraph
import com.lowagie.text.Phrase
import com.lowagie.text.Table
import com.lowagie.text.pdf.PdfWriter
import com.lowagie.text.pdf.draw.LineSeparator
import dagger.hilt.android.qualifiers.ApplicationContext
import java.awt.Color
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class ExportService @Inject constructor(
    @ApplicationContext private val context: Context
) {
    private val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())

    // Fonts
    private val titleFont = Font(Font.HELVETICA, 20f, Font.BOLD, Color(20, 20, 40))
    private val sectionFont = Font(Font.HELVETICA, 14f, Font.BOLD, Color(20, 20, 40))
    private val labelFont = Font(Font.HELVETICA, 10f, Font.BOLD, Color.BLACK)
    private val valueFont = Font(Font.HELVETICA, 10f, Font.NORMAL, Color.BLACK)
    private val footerFont = Font(Font.HELVETICA, 8f, Font.NORMAL, Color(149, 165, 166))

    private fun verdictColor(verdictName: String): Color = when (verdictName) {
        "MALICIOUS" -> Color(231, 76, 60)
        "SUSPICIOUS" -> Color(243, 156, 18)
        "CLEAN" -> Color(46, 204, 113)
        else -> Color(149, 165, 166)
    }

    fun asPlainText(result: LookupResult): String = buildString {
        appendLine("═══════════════════════════════════════")
        appendLine("  IOC LOOKUP REPORT")
        appendLine("═══════════════════════════════════════")
        appendLine()
        appendLine("IOC         : ${result.ioc}")
        appendLine("Type        : ${result.iocType.displayName}")
        appendLine("Verdict     : ${result.verdict.displayName.uppercase()}")
        appendLine("Timestamp   : ${dateFormat.format(Date(result.timestamp))}")
        appendLine()

        result.vtResult?.let { vt ->
            appendLine("── VirusTotal ──────────────────────────")
            appendLine("Detection   : ${vt.detectionLabel}")
            appendLine("Reputation  : ${vt.reputation}")
            if (vt.categories.isNotEmpty()) appendLine("Categories  : ${vt.categories.joinToString(", ")}")
            if (vt.tags.isNotEmpty()) appendLine("Tags        : ${vt.tags.joinToString(", ")}")
            appendLine()
        }

        result.abuseResult?.let { abuse ->
            appendLine("── AbuseIPDB ────────────────────────────")
            appendLine("Confidence  : ${abuse.abuseConfidenceScore}%")
            appendLine("Reports     : ${abuse.totalReports} (${abuse.numDistinctUsers} users)")
            abuse.lastReportedAt?.let { appendLine("Last Report : $it") }
            abuse.countryCode?.let { appendLine("Country     : $it") }
            abuse.isp?.let { appendLine("ISP         : $it") }
            abuse.usageType?.let { appendLine("Usage       : $it") }
            if (abuse.isTor) appendLine("Tor         : Yes")
            appendLine()
        }

        result.shodanResult?.let { sh ->
            appendLine("── Shodan ───────────────────────────────")
            if (sh.ports.isNotEmpty()) appendLine("Open Ports  : ${sh.ports.joinToString(", ")}")
            sh.country?.let { appendLine("Country     : $it") }
            sh.org?.let { appendLine("Org         : $it") }
            sh.os?.let { appendLine("OS          : $it") }
            if (sh.cves.isNotEmpty()) appendLine("CVEs        : ${sh.cves.joinToString(", ")}")
            appendLine()
        }

        result.otxResult?.let { otx ->
            appendLine("── AlienVault OTX ───────────────────────")
            appendLine("Pulses      : ${otx.pulseCount}")
            if (otx.tags.isNotEmpty()) appendLine("Tags        : ${otx.tags.take(10).joinToString(", ")}")
            if (otx.malwareFamilies.isNotEmpty()) appendLine("Malware     : ${otx.malwareFamilies.joinToString(", ")}")
            if (otx.adversaries.isNotEmpty()) appendLine("Adversaries : ${otx.adversaries.joinToString(", ")}")
            appendLine()
        }

        appendLine("═══════════════════════════════════════")
        appendLine("Generated by IOC Lookup")
    }

    fun asPdf(result: LookupResult): File {
        val dir = context.cacheDir
        val file = File(dir, "ioc_report_${System.currentTimeMillis()}.pdf")

        val document = Document()
        PdfWriter.getInstance(document, FileOutputStream(file))
        document.open()

        val accent = verdictColor(result.verdict.name)

        // Title
        document.add(Paragraph("IOC LOOKUP REPORT", titleFont))
        document.add(LineSeparator())

        // Summary table
        val summaryTable = Table(2).apply {
            width = 100f
            setWidths(floatArrayOf(30f, 70f))
            padding = 4f
            spacing = 0f
        }

        fun addRow(label: String, value: String, highlight: Boolean = false) {
            val labelCell = Cell(Phrase(label, labelFont)).apply {
                setBackgroundColor(Color(240, 240, 250))
            }
            val valFont = if (highlight) Font(Font.HELVETICA, 10f, Font.BOLD, accent) else valueFont
            val valueCell = Cell(Phrase(value, valFont))
            summaryTable.addCell(labelCell)
            summaryTable.addCell(valueCell)
        }

        addRow("IOC", result.ioc)
        addRow("Type", result.iocType.displayName)
        addRow("Verdict", result.verdict.displayName.uppercase(), highlight = true)
        addRow("Timestamp", dateFormat.format(Date(result.timestamp)))

        document.add(summaryTable)
        document.add(Paragraph("\n"))

        // Per-source sections
        fun addSection(title: String, rows: List<Pair<String, String>>) {
            document.add(Paragraph(title, sectionFont))
            document.add(LineSeparator())
            val tbl = Table(2).apply {
                width = 100f
                setWidths(floatArrayOf(35f, 65f))
                padding = 4f
                spacing = 0f
            }
            for ((lbl, vl) in rows) {
                tbl.addCell(Cell(Phrase(lbl, labelFont)))
                tbl.addCell(Cell(Phrase(vl, valueFont)))
            }
            document.add(tbl)
            document.add(Paragraph("\n"))
        }

        result.vtResult?.let { vt ->
            val rows = mutableListOf(
                "Detection" to vt.detectionLabel,
                "Reputation" to "${vt.reputation}"
            )
            if (vt.categories.isNotEmpty()) rows += "Categories" to vt.categories.joinToString(", ")
            if (vt.tags.isNotEmpty()) rows += "Tags" to vt.tags.joinToString(", ")
            addSection("VirusTotal", rows)
        }

        result.abuseResult?.let { abuse ->
            val rows = mutableListOf(
                "Confidence Score" to "${abuse.abuseConfidenceScore}%",
                "Total Reports" to "${abuse.totalReports} from ${abuse.numDistinctUsers} users"
            )
            abuse.lastReportedAt?.let { rows += "Last Reported" to it }
            abuse.isp?.let { rows += "ISP" to it }
            addSection("AbuseIPDB", rows)
        }

        result.shodanResult?.let { sh ->
            val rows = mutableListOf<Pair<String, String>>()
            if (sh.ports.isNotEmpty()) rows += "Open Ports" to sh.ports.joinToString(", ")
            sh.org?.let { rows += "Organization" to it }
            sh.country?.let { rows += "Country" to it }
            if (sh.cves.isNotEmpty()) rows += "CVEs" to sh.cves.joinToString(", ")
            if (rows.isNotEmpty()) addSection("Shodan", rows)
        }

        result.otxResult?.let { otx ->
            val rows = mutableListOf("Pulse Count" to "${otx.pulseCount}")
            if (otx.tags.isNotEmpty()) rows += "Tags" to otx.tags.take(15).joinToString(", ")
            if (otx.malwareFamilies.isNotEmpty()) rows += "Malware Families" to otx.malwareFamilies.joinToString(", ")
            addSection("AlienVault OTX", rows)
        }

        document.add(Paragraph("Generated by IOC Lookup • ${dateFormat.format(Date())}", footerFont).apply {
            alignment = Element.ALIGN_CENTER
        })

        document.close()
        return file
    }
}
